spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Agent of Sonic Cloud Real Machine Platform"
  profiles:
    active: @project.artifactId@

sonic:
  saa: 2.0.8
  sgm: 1.3.4
  sib: 1.3.20
  sas: 0.1.12
  saus: 5.7.4
